CREATE TABLE IF NOT EXISTS users
(
    user_id Integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(64) NOT NULL,
    login varchar(100) NOT NULL,
    user_name varchar(100),
    birthday date NOT NULL
);

CREATE TABLE IF NOT EXISTS friends
(
    user_id Integer REFERENCES users (user_id),
    friend_id Integer REFERENCES users (user_id),
    CONSTRAINT validate_request CHECK (user_id <> user_id),
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS ratings
(
    mpa_id Integer generated by default as identity primary key,
    mpa_name varchar(64) not null
);

CREATE TABLE IF NOT EXISTS films
(
    film_id Integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name varchar(100) not null,
    description varchar(500) not null,
    duration Integer not null,
    releaseDate date,
    mpa_id Integer REFERENCES ratings(mpa_id)
);

CREATE TABLE IF NOT EXISTS likes
(
    user_id Integer REFERENCES users(user_id),
    film_id Integer REFERENCES films(film_id),
    PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS genres
(
    genre_id Integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name varchar(100) not null
);

CREATE TABLE IF NOT EXISTS films_ganre
(
    film_id Integer REFERENCES films(film_id),
    genre_id Integer REFERENCES genres(genre_id),
    PRIMARY KEY (film_id, genre_id)
)
